# info:
# * https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
# * https://tidelift.com/subscription/how-to-connect-tidelift-with-github
github: pytest-dev
tidelift: pypi/pytest
open_collective: pytest
thanks_dev: u/gh/pytest-dev
