version: 2

python:
   install:
     # Install pytest first, then doc/en/requirements.txt.
     # This order is important to honor any pins in doc/en/requirements.txt
     # when the pinned library is also a dependency of pytest.
     - method: pip
       path: .
     - requirements: doc/en/requirements.txt

sphinx:
  configuration: doc/en/conf.py
  fail_on_warning: true

build:
  os: ubuntu-24.04
  tools:
    python: >-
      3.12
  apt_packages:
    - inkscape
  jobs:
    post_checkout:
      - git fetch --unshallow || true
      - git fetch --tags || true

formats:
  - epub
  - pdf
  - htmlzip
