# reference: https://docs.codecov.io/docs/codecovyml-reference
---

codecov:
  token: 1eca3b1f-31a2-4fb8-a8c3-138b441b50a7 #repo token

coverage:
  status:
    patch:
      default:
        target: 100%  # require patches to be 100%
    project: false
comment: false
