# reference: https://docs.codecov.io/docs/codecovyml-reference
---

codecov:
  token: 7326df64-df70-4681-ac10-e7eee7a39bd3 #repo token

coverage:
  status:
    patch:
      default:
        target: 100%  # require patches to be 100%
    project: false
comment: false
