"""
py lib / py.test setup.py file, autogenerated by gensetup.py
        
"""
import os, sys
        
from setuptools import setup
            
long_description = """

advanced testing and development support library: 

- `py.test`_: cross-project testing tool with many advanced features
- `py.execnet`_: ad-hoc code distribution to SSH, Socket and local sub processes
- `py.path`_: path abstractions over local and subversion files 
- `py.code`_: dynamic code compile and traceback printing support

Compatibility: Linux, Win32, OSX, Python versions 2.3-2.6. 
For questions please check out http://pylib.org/contact.html

.. _`py.test`: http://pylib.org/test.html
.. _`py.execnet`: http://pylib.org/execnet.html
.. _`py.path`: http://pylib.org/path.html
.. _`py.code`: http://pylib.org/code.html

(c) Holger Krekel and others, 2009  

"""
trunk = 'trunk'
def main():
    setup(
        name='py',
        description='py.test and pylib: advanced testing tool and networking lib',
        long_description = long_description, 
        version= trunk or 'trunk', 
        url='http://pylib.org', 
        license='MIT license',
        platforms=['unix', 'linux', 'osx', 'cygwin', 'win32'], 
        author='holger krekel, Guido Wesdorp, Carl Friedrich Bolz, Armin Rigo, Maciej Fijalkowski & others',
        author_email='holger at merlinux.eu, py-dev at codespeak.net',
        
        entry_points={'console_scripts': ['py.cleanup = py.cmdline:pycleanup',
                                          'py.convert_unittest = py.cmdline:pyconvert_unittest',
                                          'py.countloc = py.cmdline:pycountloc',
                                          'py.lookup = py.cmdline:pylookup',
                                          'py.rest = py.cmdline:pyrest',
                                          'py.svnwcrevert = py.cmdline:pysvnwcrevert',
                                          'py.test = py.cmdline:pytest',
                                          'py.which = py.cmdline:pywhich']},
        classifiers=['Development Status :: 5 - Production/Stable',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: MIT License',
                     'Operating System :: POSIX',
                     'Operating System :: Microsoft :: Windows',
                     'Operating System :: MacOS :: MacOS X',
                     'Topic :: Software Development :: Testing',
                     'Topic :: Software Development :: Libraries',
                     'Topic :: System :: Distributed Computing',
                     'Topic :: Utilities',
                     'Programming Language :: Python'],
        packages=['py',
                  'py.builtin',
                  'py.cmdline',
                  'py.code',
                  'py.compat',
                  'py.execnet',
                  'py.execnet.script',
                  'py.io',
                  'py.log',
                  'py.path',
                  'py.path.gateway',
                  'py.process',
                  'py.rest',
                  'py.test',
                  'py.test.dist',
                  'py.test.looponfail',
                  'py.test.plugin',
                  'py.test.web',
                  'py.thread'],
        package_data={'py': ['bin/_findpy.py',
                             'bin/env.cmd',
                             'bin/env.py',
                             'bin/py.cleanup',
                             'bin/py.convert_unittest',
                             'bin/py.countloc',
                             'bin/py.lookup',
                             'bin/py.rest',
                             'bin/py.svnwcrevert',
                             'bin/py.test',
                             'bin/py.which',
                             'bin/win32/py.cleanup.cmd',
                             'bin/win32/py.convert_unittest.cmd',
                             'bin/win32/py.countloc.cmd',
                             'bin/win32/py.lookup.cmd',
                             'bin/win32/py.rest.cmd',
                             'bin/win32/py.svnwcrevert.cmd',
                             'bin/win32/py.test.cmd',
                             'bin/win32/py.which.cmd',
                             'rest/rest.sty.template']},
        zip_safe=False,
    )

if __name__ == '__main__':
    main()
        