"""
autogenerated by gensetup.py
setup file for 'py' package based on:
        
changeset:   1165:0516498708b6
branch:      trunk
tag:         tip
user:        holger krekel <holger@merlinux.eu>
date:        Tue Jun 23 12:12:45 2009 +0200
summary:     remove TODO file (mostly done, superflous or in the issue tracker),
         
         
"""
import os, sys
        
import ez_setup
ez_setup.use_setuptools()
from setuptools import setup, Extension
        
long_description = """

advanced testing and development support library: 

- `py.test`_: cross-project testing tool with many advanced features
- `py.execnet`_: ad-hoc code distribution to SSH, Socket and local sub processes
- `py.path`_: path abstractions over local and subversion files 
- `py.code`_: dynamic code compile and traceback printing support

Compatibility: Linux, Win32, OSX, Python versions 2.3-2.6. 
For questions please check out http://pylib.org/contact.html

.. _`py.test`: http://pylib.org/test.html
.. _`py.execnet`: http://pylib.org/execnet.html
.. _`py.path`: http://pylib.org/path.html
.. _`py.code`: http://pylib.org/code.html


"""
def main():
    setup(
        name='py',
        description='py.test and pylib: advanced testing tool and networking lib',
        long_description = long_description, 
        version='1.0.x', 
        url='http://pylib.org', 
        license='MIT license',
        platforms=['unix', 'linux', 'osx', 'cygwin', 'win32'], 
        author='holger krekel, Guido Wesdorp, Carl Friedrich Bolz, Armin Rigo, Maciej Fijalkowski & others',
        author_email='holger at merlinux.eu, py-dev at codespeak.net',
        
        entry_points={'console_scripts': []},
        classifiers=['Development Status :: 4 - Beta',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: MIT License',
                     'Operating System :: POSIX',
                     'Operating System :: Microsoft :: Windows',
                     'Operating System :: MacOS :: MacOS X',
                     'Topic :: Software Development :: Testing',
                     'Topic :: Software Development :: Libraries',
                     'Topic :: System :: Distributed Computing',
                     'Topic :: Utilities',
                     'Programming Language :: Python'],
        packages=[],
        package_data={'py': []},
        zip_safe=False,
    )

if __name__ == '__main__':
    main()
        