FROM amazonlinux:2023

RUN yum update -y \
    && yum install -y python3 python3-pip \
    && yum clean all

WORKDIR /app
COPY . /app

RUN python3 -m pip install pytest \
    && python3 -m pip install -e .

CMD ["python3", "-m", "pytest", "testing"]
