FROM rockylinux:9

RUN dnf -y update \
    && dnf -y install python3 python3-pip \
    && dnf clean all

WORKDIR /app
COPY . /app

RUN python3 -m pip install pytest \
    && python3 -m pip install -e .

CMD ["python3", "-m", "pytest", "testing"]
