# syntax=docker/dockerfile:1
FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --upgrade pip \
    && pip install \
        packaging \
        pluggy<2,>=1.5 \
        attrs \
    && pip install -e .

CMD ["pytest", "testing"]
