[pytest]
strict_markers = True
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
filterwarnings =
    error::pytest.PytestWarning
    ignore:usefixtures.* without arguments has no effect:pytest.PytestWarning
    ignore:.*.fspath is deprecated and will be replaced by .*.path.*:pytest.PytestDeprecationWarning
    ignore:_pytest.python.CallSpec2 has been renamed to CallSpec.:pytest.PytestRemovedIn10Warning
